### ISSUE TITLE
Pairidaeza can't be built on floodplains

### ISSUE THREAD

**Issue by Bastes** [hanweizhang/Civ6DetailedMapTacks#1]
Hi,

Playing with a friend using your (awesome) plugin, we noticed the tacks didn't issue the little red warning sign when a pairidaeza tack was placed on floodplains (outside of the the buildable tile choice). Thought I'd signal it :)

**Comment by hanweizhang** [comment]
The validation check (red warning) only applies to wonders and districts except canals. It does not apply to improvements, like pairidaeza in your case. Thanks for signaling though.
